/* client/playstation2/bootstrap/iop_bootstrap.c
 *
 * Loads the small IOP-side drivers needed for PS2 Ethernet.
 *
 * The PS2 has two CPUs:
 *   - EE: runs this loader and the uploaded program.
 *   - IOP: owns DEV9/SMAP, the hardware path to the Ethernet adapter.
 *
 * This file asks the IOP's resident LOADFILE service to load our IRXs:
 *   1. kosdev9.irx: prepares DEV9 and exposes ReadEEPROM.
 *   2. smap.irx: runs the Ethernet driver and RPC server.
 *
 * It uses the normal SIFRPC/LOADFILE path instead of patching IOP exception
 * vectors, which proved less reliable on real hardware.
 */

#include <stdint.h>
#include <string.h>
#include <kosload/target.h>
#include "bootstrap/iop_bootstrap.h"
#include "cache.h"
#include "ee_cop0.h"
#include "ee_sif.h"
#include "iop/dev9_init_shared.h"

/* Generated bytes for kosdev9.irx.  This IOP module prepares DEV9 and
 * publishes the EEPROM-read function that smap.irx imports. */
#include "kosdev9_irx_bin.h"

/* Generated bytes for smap.irx.  This IOP module runs the Ethernet driver
 * and exposes it to the EE through RPC. */
#include "smap_irx_bin.h"

/* SMAP RPC + shared-region protocol shared with the IOP-side IRX.
 * Defines PS2_SMAP_RPC_ID, layout / status / diag response structs,
 * and the boot-status / fault-code / link-state enums. */
#include "iop/smap_protocol.h"
#include "iop_smap.h"

/* LOADFILE RPC function ID used after ee_sif_apply_lmb_patch(). */
#define LOADFILE_LOAD_BUF_CID  6

/* KSEG1 is the EE's uncached direct view of RAM.  Using it for these
 * handoff buffers avoids cache surprises and avoids the TLB entirely. */
#define EE_UNCACHED(addr)      ((void *)(((uint32_t)(addr) & 0x1fffffffu) | 0xa0000000u))
#define EE_PHYS(addr)          ((uint32_t)(addr) & 0x1fffffffu)
#define IOP_UNCACHED_BASE      0xBC000000u
#define IOP_KSEG1_BASE         0xA0000000u
#define IOP_DEV9_MBOX_ADDR     0x001F8000u
#define IOP_RAM_SIZE           0x00200000u   /* 2 MB */

#define MBOX_SENTINEL          (-99)
/* Long timeout because LOADFILE may not reply until the IRX _start function
 * finishes.  DEV9 init intentionally waits for hardware, so this needs to
 * cover a few seconds on real consoles. */
#define POLL_TIMEOUT           100000000u
#define RPC_REPLY_TIMEOUT      (POLL_TIMEOUT * 5u)

typedef struct {
    uint32_t module_ptr;
    uint32_t arg_len;
    uint8_t unused[252];
    char args[252];
} load_module_buffer_args_t;

typedef struct {
    uint32_t result;
    uint32_t modres;
} load_module_buffer_result_t;

static volatile load_module_buffer_args_t load_args __attribute__((aligned(64)));
static volatile load_module_buffer_result_t load_result __attribute__((aligned(64)));
static volatile ee_sif_rpc_client_t ee_loadfile_client __attribute__((aligned(64)));

static const char *phase1_status = "PHASE1: UNTRIED";

/* Set after smap.irx is loaded.  ps2_bootstrap_iop_smap_init() checks this
 * instead of loading the same IRX twice. */
static int g_smap_bootstrap_result = -1;

static void ee_delay(unsigned long loops);

static void set_phase1_status(const char *s)
{
    /* Surface the latest bootstrap phase so adapter_get_phase_status
     * can prefix it onto network_init_error_msg.  When DEV9 init
     * fails the user sees e.g. "PHASE1: IOP RESET FAIL | DEV9 INIT
     * FAILED" on the red error screen instead of just the umbrella
     * "DEV9 INIT FAILED" — telling them which sub-step died. */
    phase1_status = (s != 0) ? s : "PHASE1: UNKNOWN";
}

static void reset_ee_sif_session(void)
{
    ee_sif_set_status_callback(set_phase1_status);
    ee_sif_reset_state();
    memset((void *)&ee_loadfile_client, 0, sizeof(ee_loadfile_client));
}

static void ee_delay(unsigned long loops)
{
    volatile unsigned long i;
    for (i = 0; i < loops; i++)
        ;
}


void interrupt_handler_c(void);
void interrupt_handler_c(void)
{
    uint32_t cause = ee_cop0_read_cause();
    uint32_t status = ee_cop0_read_status();

    if ((cause & EE_COP0_CAUSE_INT5_TIMER) != 0u)
        ee_cop0_write_compare(0xffffffffu);

    /* No EE interrupt source is required for the PS2 loader's polling SIF
     * path.  If an inherited timer/interrupt enable leaks through, return to
     * the interrupted code with CPU interrupts masked instead of spinning in
     * the interrupt vector forever. */
    ee_cop0_write_status(status & ~(EE_COP0_STATUS_IE |
                                    EE_COP0_STATUS_INT5_TIMER));
}

int ps2_bootstrap_iop_dma_write(uint32_t iop_dest, const void *src,
                                uint32_t size)
{
    if (iop_dest >= IOP_RAM_SIZE)
        return -1;
    if (size != 0u && iop_dest + size > IOP_RAM_SIZE)
        return -1;

    return ee_sif_iop_write((void *)iop_dest, src, size);
}


static void capture_diag(iop_dev9_diag_t *diag,
                         volatile const struct iop_mailbox *mbox)
{
    diag->result = mbox->result;
    diag->rev = mbox->rev;
    diag->power = mbox->power;
    diag->map = mbox->map;
    diag->presence = mbox->presence;
}

/* ============================================================
 * LMB patch — clean-room reimplementation
 *
 * The BIOS LOADFILE module's RPC dispatcher rejects function
 * index 6 (LF_F_MOD_BUF_LOAD = "load IRX from EE buffer"). The
 * dispatcher at LOADFILE :0x4d4 (or :0x4c4 in older SDK comments)
 * does:
 *
 *     27bdffe8  addiu $sp, -24
 *     2c820006  sltiu $v0, $a0, 6      ; reject CID >= 6
 *     14400003  bnez  $v0, +12
 *     afbf0010  sw    $ra, 16($sp)
 *     08000XXX  j     error_path        ; CID >= 6 falls here
 *     00001021  move  $v0, zero
 *     ...                               ; CID < 6 dispatches via JT
 *     3c010000  lui   $at, JT_HI
 *     00220821  addu  $at, $at, $v0     ; v0 = CID*4
 *     8c22XXXX  lw    $v0, JT_LO($at)   ; jump_table[CID]
 *     0040f809  jalr  $v0
 *
 * To enable CID 6 we:
 *   1. Find the dispatcher in IOP RAM by signature.
 *   2. Find modload's export table by signature (marker
 *      0x41C00000 + name "modload"); read exports[10] =
 *      LoadModuleBuffer and exports[8] = StartModule.
 *   3. Allocate IOP heap for a 32-instruction stub.
 *   4. Build the stub (calls LoadModuleBuffer then StartModule
 *      with mode "LBbyEE").
 *   5. SIF DMA the stub into IOP heap.
 *   6. Direct-write the dispatcher's sltiu instruction to
 *      "$a0, 7" (allow CID 6) and write the new jump-table
 *      entry past the existing 6.
 *
 * Reference: this is a clean-room reimplementation. The IOP
 * relocation engine and module table layout are derived from
 * disassembling scph39001.bin's BIOS LOADCORE/LOADFILE/MODLOAD. */

#define IOP_RAM_BASE_EE      0xBC000000u   /* EE-uncached view of IOP RAM */
#define LF_DISPATCH_SIG_0    0x27bdffe8u   /* addiu sp,-24 */
#define LF_DISPATCH_SIG_1A   0x2c820006u   /* sltiu v0,a0,6  — stock */
#define LF_DISPATCH_SIG_1B   0x2c820007u   /* sltiu v0,a0,7  — already LMB-patched */
#define LF_DISPATCH_SIG_2    0x14400003u   /* bnez v0,+12 */
#define LF_DISPATCH_SIG_3    0xafbf0010u   /* sw ra,16(sp) */
#define LIBLIST_EXPORT_MARK  0x41C00000u   /* loadcore export-table marker */
#define MODLOAD_NAME_W0      0x646F6Du     /* "modl" — first 3 chars + 'l' high byte */
                                           /* will be checked as 32-bit "modl" */

/* Read a 32-bit word from IOP RAM via the EE uncached alias. */
static inline uint32_t iop_read_word(uint32_t iop_addr)
{
    return *(volatile uint32_t *)(IOP_RAM_BASE_EE + (iop_addr & 0x1FFFFFFu));
}

/* Direct-write a 32-bit word to IOP RAM via the EE uncached alias. */
static inline void iop_write_word(uint32_t iop_addr, uint32_t value)
{
    *(volatile uint32_t *)(IOP_RAM_BASE_EE + (iop_addr & 0x1FFFFFFu)) = value;
}


/* ============================================================
 * IOP module-list dump probe
 * ============================================================
 *
 * Walks IOP RAM looking for irx_export_table headers (magic
 * 0x41C00000) and dumps a per-library listing with approximate
 * memory footprint, estimated from the gap between consecutively
 * located libraries when sorted by IOP address.
 *
 * "Library" and "module" aren't strictly 1:1 — an IRX may register
 * multiple libraries — but in practice nearly every BIOS-loaded IRX
 * registers exactly one library named the same as the module, so this
 * yields a usable accounting of default-loaded modules and their
 * footprint.
 *
 * Output format (one line per library, then a summary):
 *     M <name8>     <kb>K
 *     TOT: <N> libs <total_kb>K
 *
 * Default-build: compiled but not invoked (zero runtime cost).
 * Enable for a one-shot dump by building with
 *   -DKOSLOAD_DUMP_IOP_MODULES — the call site is in
 * ps2_bootstrap_iop_dev9_init() between POST-IRQ and apply_lmb_patch.
 */
#define IRX_EXPORT_MAGIC     0x41C00000u
#define DUMP_MODS_MAX        80u
#define DUMP_LINE_HOLD       30000000u    /* ~1 s per line */

typedef struct {
    char     name[9];      /* 8 ASCII + NUL */
    uint32_t addr;         /* IOP address of the export-table magic */
} dump_mod_t;

static dump_mod_t dump_mods[DUMP_MODS_MAX];
static unsigned int dump_mods_count;

static void dump_extract_name(uint32_t addr, char *out)
{
    uint32_t words[2];
    int i;
    int saw_zero = 0;

    words[0] = iop_read_word(addr + 0x0Cu);
    words[1] = iop_read_word(addr + 0x10u);

    for (i = 0; i < 8; i++) {
        unsigned char c;

        if (saw_zero) {
            out[i] = '\0';
            continue;
        }
        c = (unsigned char)(words[i / 4] >> ((i & 3) * 8));
        if (c == 0) {
            saw_zero = 1;
            out[i] = '\0';
            continue;
        }
        if (c < 0x20 || c >= 0x7F) c = '?';
        out[i] = (char)c;
    }
    out[8] = '\0';
}

/* Validate a candidate SLIB header.  Filters out occurrences of the
 * magic value 0x41C00000 that aren't real export tables (random data,
 * the constant baked into LOADCORE itself, etc.). */
static int dump_is_valid_slib(uint32_t addr)
{
    uint32_t version_mode;
    uint32_t first_fn;
    uint32_t low, hi;

    if (addr + 0x18u >= IOP_RAM_SIZE)
        return 0;

    /* version|mode word: low 16 bits version (non-zero for real),
     * high 16 bits mode (small value, almost always 0). */
    version_mode = iop_read_word(addr + 0x08u);
    if ((version_mode & 0xFFFFu) == 0u) return 0;
    if ((version_mode >> 16) > 0xFFu)   return 0;

    /* First exported function pointer should be a non-zero IOP RAM
     * address.  Accept either physical (0x00xxxxxx), KSEG0
     * (0x80xxxxxx), or KSEG1 (0xA0xxxxxx) form. */
    first_fn = iop_read_word(addr + 0x14u);
    if (first_fn == 0u) return 0;
    low = first_fn & 0x1FFFFFFu;
    hi  = first_fn & 0xE0000000u;
    if (low >= IOP_RAM_SIZE) return 0;
    if (hi != 0u && hi != 0x80000000u && hi != 0xA0000000u) return 0;

    return 1;
}

void ps2_bootstrap_dump_iop_modules(void)
{
    uint32_t addr;
    unsigned int i, j;
    uint32_t total_kb = 0u;
    static char summary_line[40];
    char *summary_p;
    unsigned int summary_n;
    uint32_t summary_kb;

    set_phase1_status("MOD DUMP: SCAN");
    ee_delay(20000000u);

    dump_mods_count = 0u;

    /* Skip the first 64 KB of IOP RAM so we don't spend time on the
     * BIOS-internal LOADCORE / kernel area where false-positive magic
     * matches are likely.  Real exported libraries live in the
     * module-load region above that. */
    for (addr = 0x00010000u;
         addr + 0x18u < IOP_RAM_SIZE && dump_mods_count < DUMP_MODS_MAX;
         addr += 4u) {
        if (iop_read_word(addr) != IRX_EXPORT_MAGIC) continue;
        if (!dump_is_valid_slib(addr)) continue;

        dump_extract_name(addr, dump_mods[dump_mods_count].name);
        dump_mods[dump_mods_count].addr = addr;
        dump_mods_count++;
    }

    /* Sort by addr (insertion sort, n < 80). */
    for (i = 1u; i < dump_mods_count; i++) {
        dump_mod_t key = dump_mods[i];
        for (j = i; j > 0u && dump_mods[j - 1u].addr > key.addr; j--)
            dump_mods[j] = dump_mods[j - 1u];
        dump_mods[j] = key;
    }

    /* Emit one line per library with approximate size. */
    for (i = 0u; i < dump_mods_count; i++) {
        static char line[40];
        uint32_t this_addr = dump_mods[i].addr;
        uint32_t next_addr;
        uint32_t kb;
        char *p = line;
        const char *n;
        unsigned int cnt;

        next_addr = (i + 1u < dump_mods_count)
            ? dump_mods[i + 1u].addr
            : IOP_RAM_SIZE;
        kb = (next_addr - this_addr) / 1024u;
        total_kb += kb;

        /* "M <name8>     <kbb>K" — pad name field to 8 wide, kb to 4 wide */
        *p++ = 'M'; *p++ = ' ';
        n = dump_mods[i].name;
        for (cnt = 0u; cnt < 8u && n[cnt] != '\0'; cnt++) *p++ = n[cnt];
        for (; cnt < 8u; cnt++) *p++ = ' ';
        *p++ = ' ';
        *p++ = (kb >= 1000u) ? (char)('0' + (kb / 1000u) % 10u) : ' ';
        *p++ = (kb >=  100u) ? (char)('0' + (kb /  100u) % 10u) : ' ';
        *p++ = (kb >=   10u) ? (char)('0' + (kb /   10u) % 10u) : ' ';
        *p++ = (char)('0' + kb % 10u);
        *p++ = 'K';
        *p   = '\0';

        set_phase1_status(line);
        ee_delay(DUMP_LINE_HOLD);
    }

    /* Summary line. */
    summary_p = summary_line;
    summary_n = dump_mods_count;
    summary_kb = total_kb;

    *summary_p++ = 'T'; *summary_p++ = 'O'; *summary_p++ = 'T';
    *summary_p++ = ':'; *summary_p++ = ' ';
    if (summary_n >= 100u)
        *summary_p++ = (char)('0' + (summary_n / 100u) % 10u);
    if (summary_n >=  10u)
        *summary_p++ = (char)('0' + (summary_n /  10u) % 10u);
    *summary_p++ = (char)('0' + summary_n % 10u);
    *summary_p++ = ' '; *summary_p++ = 'l'; *summary_p++ = 'i';
    *summary_p++ = 'b'; *summary_p++ = 's'; *summary_p++ = ' ';
    if (summary_kb >= 1000u)
        *summary_p++ = (char)('0' + (summary_kb / 1000u) % 10u);
    if (summary_kb >=  100u)
        *summary_p++ = (char)('0' + (summary_kb /  100u) % 10u);
    if (summary_kb >=   10u)
        *summary_p++ = (char)('0' + (summary_kb /   10u) % 10u);
    *summary_p++ = (char)('0' + summary_kb % 10u);
    *summary_p++ = 'K'; *summary_p++ = 'B';
    *summary_p   = '\0';

    set_phase1_status(summary_line);
    ee_delay(120000000u);   /* ~3.5 s for the summary */
}

static int load_dev9_irx(void)
{
    volatile struct iop_mailbox *mbox;
    volatile load_module_buffer_result_t *result_view;
    void *irx_iop_addr;
    uint32_t irx_qw_size;

    mbox = (volatile struct iop_mailbox *)(IOP_UNCACHED_BASE + IOP_DEV9_MBOX_ADDR);
    memset((void *)&load_args, 0, sizeof(load_args));
    memset((void *)&load_result, 0, sizeof(load_result));

    mbox->cmd = 0;
    mbox->result = MBOX_SENTINEL;
    mbox->rev = 0;
    mbox->power = 0;
    mbox->map = 0;
    mbox->presence = 0;

    /* Round IRX size up to a 16-byte (qword) boundary before
     * alloc + DMA. SIF DMA is qword-granular at the hardware
     * level, so the heap reservation, dcache flush, and DMA size
     * all need to agree on the same byte count. */
    irx_qw_size = (kosdev9_irx_bin_len + 15u) & ~15u;

    irx_iop_addr = ee_sif_alloc_iop_heap(irx_qw_size);
    if (irx_iop_addr == 0) {
        //set_phase1_status("PHASE1: HEAP ALLOC FAIL");
        return -1;
    }

    if (ee_sif_iop_write(irx_iop_addr, kosdev9_irx_bin,
                         irx_qw_size) < 0) {
        //set_phase1_status("PHASE1: IRX DMA FAIL");
        return -1;
    }

    load_args.module_ptr =
        IOP_KSEG1_BASE | (((uint32_t)irx_iop_addr) & 0x1fffffu);
    load_args.arg_len = 0u;

    cache_flush_dc((const void *)&load_args, sizeof(load_args));
    cache_flush_dc((const void *)&load_result, sizeof(load_result));

    if (ee_sif_rpc_call(&ee_loadfile_client, LOADFILE_LOAD_BUF_CID,
                        (const void *)&load_args, sizeof(load_args),
                        (void *)&load_result, sizeof(load_result)) < 0) {
        /* sifrpc_call sets a more specific status before returning
         * negative — "RPC CALL" or "CALL NO REPLY".  Don't clobber
         * it with the generic "LOAD RPC FAIL", which hides whether
         * the issue was the send-cmd path or a poll timeout. */
        return -1;
    }

    /* Surface the case where SIF RPC succeeded but IOP-side LMB
     * returned a negative module id (out of memory / bad ELF / bad
     * relocations / LinkImports rejected / etc.).  Without this the
     * caller's generic "LOAD FAIL" overwrite (see below) hides which
     * sub-step actually failed. */
    result_view = (volatile load_module_buffer_result_t *)EE_UNCACHED(&load_result);
    if ((int)result_view->result < 0) {
        //set_phase1_status("PHASE1: LMB REJECTED");
        return (int)result_view->result;
    }

    return (int)result_view->result;
}

int ps2_bootstrap_iop_dev9_init(iop_dev9_diag_t *diag)
{
    volatile const struct iop_mailbox *mbox;
    unsigned int i;
    int result;
    int reset_rc;
    int lmb_rc;
    void *smap_irx_iop_addr;
    uint32_t smap_irx_qw_size;

    if (diag == 0)
        return -1;

    memset(diag, 0, sizeof(*diag));
    reset_ee_sif_session();
    set_phase1_status("PHASE1: START");

    /* Best-effort BOOTEND wait — on real hardware BIOS EESYNC sets the
     * flag before any user ELF runs, so the call returns immediately.
     * Under PCSX2 the BIOS HLE may skip the SMFLAG write entirely; the
     * call then spins out its full timeout (slow but bounded) and
     * returns -1.  We no longer treat absence as fatal — ee_sif_cmd_init
     * below is the real gate: it reads SIF_SYSREG_SUBADDR (set by
     * IOP-side SIFCMD when ready) and returns -2 if the IOP isn't
     * talking. */
    //(void)ee_sif_wait_iop_bootend();

    if (ee_sif_cmd_init() < 0) {
        set_phase1_status("PHASE1: SIFCMD FAIL (no SUBADDR)");
        diag->result = -21;
        return -21;
    }
    set_phase1_status("PHASE1: SIFCMD1 OK");

    /* Reset the IOP unconditionally.  This wipes any stale IOP state —
     * launcher-injected modules / patches (FMCB / wLE pre-patched
     * LOADFILE etc.) on a cold boot, OR the half-finished SIF session
     * left by the previous loader on a -F firmware-update handoff.  Both
     * are the same problem: a dirty IOP we don't own yet.  This single
     * path serves both, so there is no -F-specific detection or marker.
     * Needs SIFCMD up first (reset is triggered by sending
     * EE_SIF_CMD_IOP_RESET); ee_sif_iop_reset() is synchronous — it
     * waits out the IOP re-IPL — then we re-init against the fresh IOP. */
    set_phase1_status("PHASE1: IOP RESET");
    reset_rc = ee_sif_iop_reset(0);
    if (reset_rc < 0) {
        set_phase1_status("PHASE1: IOP RESET FAIL");
        diag->result = -26;
        return -26;
    }
    set_phase1_status("PHASE1: IOP RESET OK");

    /* Re-init SIFCMD/SIFRPC against the post-reset IOP.  All previous
     * client bindings, packet pools, and IOP-side service IDs are
     * gone so this is a fresh handshake. */
    if (ee_sif_cmd_init() < 0) {
        set_phase1_status("PHASE1: SIFCMD2 FAIL");
        diag->result = -27;
        return -27;
    }
    set_phase1_status("PHASE1: SIFCMD2 OK");

    if (ee_sif_rpc_init() < 0) {
        set_phase1_status("PHASE1: SIFRPC FAIL");
        diag->result = -22;
        return -22;
    }
    set_phase1_status("PHASE1: SIFRPC OK");

    if (ee_sif_rpc_bind_retry(&ee_loadfile_client,
                              EE_SIF_LOADFILE_RPC_ID, 64u) < 0) {
        set_phase1_status("PHASE1: LOADFILE BIND FAIL");
        diag->result = -23;
        return -23;
    }
    set_phase1_status("PHASE1: LOADFILE BIND OK");

    /* Interrupt-driven SIF receive is intentionally DISABLED here.
     *
     * ee_irq_test.elf already proved the exception-vector + IE/EIE/IM2
     * path works (one timer-driven IRQ fired cleanly).  Calling
     * enable_sif0_interrupt() here previously caused subsequent GIF
     * DMA to wedge — the ISR W1Cs every pending D_STAT lower-16 bit
     * including DMAC channels we don't own, and that interferes with
     * channels in flight elsewhere.  The bootstrap's SIF receive is
     * polling-based, so IRQs aren't required for forward progress.
     * Re-enable once we have a properly scoped DMAC ISR. */
    //set_phase1_status("PHASE1: IRQ SKIPPED");

    //set_phase1_status("PHASE1: POST-IRQ");

#ifdef KOSLOAD_DUMP_IOP_MODULES
    /* Diagnostic dump of every IRX-exported library currently in IOP
     * RAM, with an approximate size estimate per module.  Enabled by
     * building with -DKOSLOAD_DUMP_IOP_MODULES; not on the default
     * critical path because it adds ~30-60 s of screen output. */
    ps2_bootstrap_dump_iop_modules();
#endif

    /* Apply the LMB patch — BIOS LOADFILE doesn't support CID 6
     * (loadfile_loadmodulebuffer) by default. Without this, our
     * IRX gets loaded but relocations are never applied — the
     * `lui $r, 0; addiu $r, $r, 0` pairs encoding `&function`
     * stay at zero, and `jal 0` halts the IOP. */
    set_phase1_status("PHASE1: LMB patch");
    lmb_rc = ee_sif_apply_lmb_patch();
    if (lmb_rc < 0) {
        set_phase1_status("PHASE1: LMB patch FAIL");
        diag->result = -25;
        return -25;
    }
    set_phase1_status("PHASE1: LMB patch OK");

    set_phase1_status("PHASE1: kosdev9.irx LMB load");
    result = load_dev9_irx();
    if (result < 0) {
        /* load_dev9_irx() always set a more-specific status before
         * returning negative — HEAP ALLOC FAIL / IRX DMA FAIL / LOAD
         * RPC FAIL / LMB REJECTED.  Don't clobber it with a generic
         * "LOAD FAIL".  The previous check `phase1_status[0] != 'L'`
         * was a bug: every status starts with "PHASE1: " so the first
         * char is always 'P', so the overwrite always fired and hid
         * which sub-step actually failed. */
        set_phase1_status("PHASE1: kosdev9.irx LOAD FAIL");
        diag->result = -24;
        return -24;
    }
    set_phase1_status("PHASE1: kosdev9.irx LOADED");

    set_phase1_status("PHASE1: POLL MBOX");
    mbox = (volatile const struct iop_mailbox *)(IOP_UNCACHED_BASE + IOP_DEV9_MBOX_ADDR);
    for (i = 0; i < POLL_TIMEOUT; i++) {
        result = mbox->result;
        if (result != MBOX_SENTINEL)
            break;
    }

    capture_diag(diag, mbox);
    if (result == MBOX_SENTINEL) {
        set_phase1_status("PHASE1: MBOX TIMEOUT");
        diag->result = -11;
        return -11;
    }

    set_phase1_status("PHASE1: DONE");

    /* Load smap.irx.  If this succeeds, normal network init will bind RPC
     * to it later and fetch the shared-memory layout. */
    smap_irx_qw_size = (smap_irx_bin_len + 15u) & ~15u;
    smap_irx_iop_addr = ee_sif_alloc_iop_heap(smap_irx_qw_size);
    if (smap_irx_iop_addr == 0) {
        set_phase1_status("PHASE1: SMAP HEAP FAIL");
    } else if (ee_sif_iop_write(smap_irx_iop_addr, smap_irx_bin,
                                smap_irx_qw_size) < 0) {
        set_phase1_status("PHASE1: SMAP DMA FAIL");
    } else {
        memset((void *)&load_args, 0, sizeof(load_args));
        memset((void *)&load_result, 0, sizeof(load_result));

        load_args.module_ptr =
            IOP_KSEG1_BASE |
            (((uint32_t)smap_irx_iop_addr) & 0x1fffffu);
        load_args.arg_len = 0u;

        cache_flush_dc((const void *)&load_args, sizeof(load_args));
        cache_flush_dc((const void *)&load_result, sizeof(load_result));

        /* Clear the SMAP RPC-ready sentinel BEFORE the LMB load so the
         * only thing that can flip it to READY is this fresh smap.irx's
         * smap_rpc_thread (after RpcRegister + queue workaround).  On -F
         * the IOP was reset but its RAM is not zeroed, so a previous
         * session's READY could otherwise survive and let ps2_smap_init
         * bind before the new server is registered — the exact race this
         * fixes.  SBUS-bridge uncached alias, same as the dev9 mailbox. */
        *(volatile uint32_t *)(IOP_UNCACHED_BASE | PS2_SMAP_READY_IOP_PHYS) =
            PS2_SMAP_NOTREADY_MAGIC;

        set_phase1_status("PHASE1: smap.irx LMB load");
        if (ee_sif_rpc_call(&ee_loadfile_client,
                            LOADFILE_LOAD_BUF_CID,
                            (const void *)&load_args,
                            sizeof(load_args),
                            (void *)&load_result,
                            sizeof(load_result)) < 0) {
            set_phase1_status("PHASE1: SMAP NO REPLY");
            g_smap_bootstrap_result = -1;
        } else {
            volatile load_module_buffer_result_t *result_view =
                (volatile load_module_buffer_result_t *)
                EE_UNCACHED(&load_result);
            if ((int)result_view->result < 0) {
                set_phase1_status("PHASE1: SMAP LMB REJECTED");
                g_smap_bootstrap_result = -1;
            } else {
                set_phase1_status("PHASE1: SMAP LOADED");
                g_smap_bootstrap_result = 0;
            }
        }
    }

    diag->result = result;
    return result;
}

const char *ps2_bootstrap_phase1_status(void)
{
    return phase1_status;
}

int ps2_bootstrap_iop_smap_init(void)
{
    int rpc_rc;

    /* The SMAP IRX is LMB-loaded inline by ps2_bootstrap_iop_dev9_init
     * (legacy ordering, pre-RPC migration).  After the IRX is resident,
     * we still need to bind the RPC client + fetch the shared-region
     * layout via GET_LAYOUT.  Cache the result so subsequent calls are
     * cheap. */
    static int g_rpc_bound = 0;

    if (g_smap_bootstrap_result < 0)
        return g_smap_bootstrap_result;

    if (g_rpc_bound)
        return 0;

    rpc_rc = ps2_smap_init();
    if (rpc_rc < 0) {
        g_smap_bootstrap_result = -1;
        return rpc_rc;
    }

    g_rpc_bound = 1;
    return 0;
}
